version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reactive-app
    ports:
      - "8080:8080"
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://host.docker.internal:5432/users_db
      SPRING_R2DBC_USERNAME: user
      SPRING_R2DBC_PASSWORD: password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
