version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reactive-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://db:5432/users_db
      SPRING_R2DBC_USERNAME: user
      SPRING_R2DBC_PASSWORD: password

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
