version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reactive-app
    ports:
      - "8080:8080"
    environment:
      SPRING_R2DBC_URL: jdbc:postgresql://localhost:5432/postgres
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
