version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"   # Exposing port for external access (can be omitted if you only need internal access)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    container_name: reactive-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://db:5432/users_db
      SPRING_R2DBC_USERNAME: user
      SPRING_R2DBC_PASSWORD: password

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
