spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/userDb
    username: postgres
    password: root
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/userDb
    user: postgres
    password: root
    locations: classpath:db/migration
    baseline-on-migrate: true
