spring:
  r2dbc:
    url: r2dbc:postgresql://db:5432/postgres     # Reference the db container by its service name
    username: postgres
    password: root
  app:
    database:
      name: users_db
  flyway:
    enabled: true

